"""Initial setup with auth attempt

Revision ID: 49165965027b
Revises: 
Create Date: 2025-03-18 13:26:00.103094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49165965027b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('movie_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_title', sa.String(length=200), nullable=False),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_rating_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_title', name='uq_user_movie_rating')
    )
    op.create_table('watchlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_title', sa.String(length=200), nullable=False),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_watchlist_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_title', name='uq_user_movie_watchlist')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_item')
    op.drop_table('movie_rating')
    op.drop_table('user')
    # ### end Alembic commands ###
